version: 1.0.{build}
branches:
  only:
  - master
  - dev
  - staging
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal